### PR TITLE
Deploy binaries automatically

### PR DESCRIPTION
**Pull request by Luni-4**
This PR deploys automatically the `mdbook-katex` binaries for `Linux` and `MacOS` operating systems.

To run the deploy action, you just need to push a tag.

You can find a fake release [here](https://github.com/Luni-4/mdbook-katex/releases/tag/v0.2.8).

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by lzanini** [comment]
Hello, 

Thank you for the PR! 

Is there a reason why you didn't add a release for windows as well?

**Comment by Luni-4** [comment]
Hello @lzanini! 

Yep, for this reason: https://github.com/theduke/quickjs-rs/issues/93

**Comment by Luni-4** [comment]
Thanks for merging my PR @lzanini, very appreciated! :)

**Comment by lzanini** [comment]
You're welcome :+1:

**Pull request merged**
